
project_id = "stehjqdbncykevpokcvj"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used in emails.
site_url = "https://yeildsocials.com"
enabled = true
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = [
  "https://yeildsocials.com", 
  "https://yeildsocials.com/auth/callback", 
  "https://yeildsocials.com/dashboard", 
  "https://yeildsocials.com/brand-dashboard", 
  "https://yeildsocials.com/admin", 
  "https://yeildsocials.com/login",
  "https://yeildsocials.com/reset-password",
  "https://yeild.lovable.app", 
  "https://yeild.lovable.app/auth/callback", 
  "https://yeild.lovable.app/dashboard", 
  "https://yeild.lovable.app/brand-dashboard", 
  "https://yeild.lovable.app/admin", 
  "https://yeild.lovable.app/login",
  "https://yeild.lovable.app/reset-password",
  "https://lovable.dev"
]

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.flutterwave-webhook]
verify_jwt = false

[functions.process-settlements]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.flutterwave-payment]
verify_jwt = true

[functions.flutterwave-verify]
verify_jwt = true

[functions.flutterwave-transfer]
verify_jwt = true

[functions.admin-operations]
verify_jwt = true

[functions.send-brand-confirmation-email]
verify_jwt = false

[functions.send-user-notification]
verify_jwt = true

[functions.email-service]
verify_jwt = false
