
project_id = "stehjqdbncykevpokcvj"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used in emails.
site_url = "https://yeildsocials.com"
enabled = true
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = [
  "https://yeildsocials.com/auth", 
  "https://yeildsocials.com/brand-dashboard", 
  "https://yeildsocials.com/dashboard", 
  "https://yeildsocials.com/onboarding",
  "https://yeildsocials.com/admin",
  "https://yeildsocials.com/verify",
  "https://yeildsocials.com/reset-password",
  "https://yeildsocials.com/update-password",
  "https://601caf62-c867-4152-87f9-fa5869c55de0.lovableproject.com",
  "https://601caf62-c867-4152-87f9-fa5869c55de0.lovableproject.com/auth",
  "https://601caf62-c867-4152-87f9-fa5869c55de0.lovableproject.com/brand-dashboard",
  "https://601caf62-c867-4152-87f9-fa5869c55de0.lovableproject.com/dashboard",
  "https://601caf62-c867-4152-87f9-fa5869c55de0.lovableproject.com/onboarding"
]

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

[auth.security]
# Enable additional security features for production
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.payment-webhook]
verify_jwt = false

[functions.flutterwave-payment]
verify_jwt = true

[functions.flutterwave-verify]
verify_jwt = true

[functions.flutterwave-transfer]
verify_jwt = true

[functions.admin-operations]
verify_jwt = true

[functions.send-brand-confirmation-email]
verify_jwt = false

[functions.send-user-notification]
verify_jwt = true

[functions.verify-bank-account]
verify_jwt = false
